contexts:
    nganluong:
        nganluong:
            merchant_id:        %nganluong.merchant_id%
            merchant_password:  %nganluong.merchant_password%
            receiver_email:     %nganluong.receiver_email%
            sandbox:            %nganluong.sandbox%
            sandbox_url:        %nganluong.sandbox_url%
